### ISSUE TITLE
Works only for sf in current dir

### ISSUE THREAD

**Issue by fiee** [raboof/sfarkxtc#5] opened 2015-04-09 06:05 UTC
If you try to call the tool with a complete path like

```
./sfarkxtc /Users/me/SoundFonts/Fluid.sfArk /Users/me/SoundFonts/Fluid.sf2
```

it fails with errorcode 9 (at least on OSX). It works, if you cd to the soundfont’s directory.

Please at least document, that it doesn’t work with paths, but only with files.

**Comment by raboof** [comment] 2015-04-09 06:23
Indeed you currently have to cd to the target directory. I'd prefer fixing that ;)

**Comment by AntiMatterAMA** [comment] 2018-12-28 16:55
Confirmed on Ubuntu Budgie 19.04. Everything has to be in this folder, and you have to type the relative path from there. If you type the absolute path in, you get the errcode 9.

**Comment by moltenform** [comment] 2019-05-12 06:21
I have a fix for this, in my fork at https://github.com/moltenform/sfarkxtc-windows
I can make a PR if it would be useful.
I also fixed the name handling to make it consistent (e.g. without my patch, notes files are written out to a path based on the original sf2 filename).

**Comment by raboof** [comment] 2019-05-12 09:20
A PR would be great!

**Comment by moltenform** [comment] 2019-05-12 20:02
PR sent,
https://github.com/raboof/sfArkLib/pull/13

**Comment by moltenform** [comment] 2019-05-26 20:03
Thoughts?

**Comment by moltenform** [comment] 2020-07-15 16:58
I think this issue can be closed, my PR back in june 2019 (https://github.com/raboof/sfArkLib/pull/13) fixes the issue.

**Comment by raboof** [comment] 2020-07-15 18:10
Indeed looks like we forgot to close this one, thanks again!

**Closed by raboof** 2020-07-15 18:10 UTC
Labels: enhancement, help wanted
